### ISSUE TITLE
Can we use ui scripts on spesific projects? 

### ISSUE THREAD

**Issue by elnuggs0** [gurock/testrail-custom#12]
I can see we use includes and excludes for attributes defining which page to have it in but nothing about specific projects. 

Example if I wanted to post to slack but only from one project how would I do that?

**Comment by Jteve-Sobs** [comment]
You can use the context information `uiscripts.context.project`. See this [page ](https://support.gurock.com/hc/en-us/articles/7344009893908-UI-scripts-introduction#writing-ui-scripts-0-0).
